### ISSUE TITLE
:)

### ISSUE THREAD

**Issue by vsoch** [lindaelwei/lindaelwei.github.io#1]
Awesome! Please reach out if you want/need any help. :)

**Comment by lindaelwei** [comment]
Thanks! I really appreciate the whole idea of Experimental Factory -- I'm setting up for the first experiment of my PhD right now and having original code to reference and build upon has saved me so much headache 👍

**Comment by vsoch** [comment]
Awesome!! Haha, yeah we went through the same thing, and even two rounds of the Experiment Factory until the current (container-based) version that I hope fits the bill! I'll close the issue, and please re-open (and I'll get a notification from Github) if you need any help :) Best of luck with your PhD!
